compile:
	@xelatex func_spec.tex
	@rm func_spec.aux func_spec.lof func_spec.log func_spec.lot func_spec.out func_spec.toc

clean:
	@rm func_spec.aux func_spec.lof func_spec.log func_spec.lot func_spec.out func_spec.toc

